server:
  port: 8080
  servlet:
    session:
      persistent: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity-service?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

api:
  prefix: api/v1
jwt:
  expiration: 36000 #10hours = 10* 60 * 60
  signerKey: "jZHPeU9yw9x-JpCoXxVbZ5nUEZHT4f6aA-m5MtCVVEO66WRiC7kerrOKTOiqWM4IcaisVoVz_M_OkvUBPFtDXw"
  refresh-expiration: 604800 #7days = 7 * 24 * 60 * 60

